server:
  port: 10086

github:
  client:
    id: 6ab47e4c530100275865
    secret: 5b3d4a11820b01df03a8527d6987c0142c63a66b

  redirect:
    uri: http://localhost:10086/callback


spring:
  datasource:
    username: root
    password: Hrs12345
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:22222/hrs_community
